services:
  postgres:
    container_name: push-notification-scheduled-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: push-notification-scheduled
    volumes:
      - ./data/pg:/data/postgres
